libname day3 "F:\Student\Mahesh\Data1";
proc sort data = day3.candy out = candy01;
by brand;
run;
proc sort data = day3.candy out = candy01;
by descending brand;
run;
proc sort data = day3.candy_sales_summary out = candy02 nodupkey;
by subcategory;
run;
proc sort data = day3.candy_sales_summary out = candy03 nodup;
by subcategory;
run;
proc freq data = day3.candy;
run;
proc freq data = day3.candy;
tables brand name;
run;
proc freq data = day3.candy_sales_summary;
tables category * subcategory;
run;
proc freq data = day3.candy_sales_summary;
tables category * subcategory/nocol norow;
run;
proc freq data = day3.candy_sales_summary;
tables category * subcategory/nopercent nofreq;
run;
proc freq data = day3.candy_sales_summary;
tables fiscal_year * category * subcategory;
run;
proc freq data = day3.candy_sales_summary;
tables fiscal_year * fiscal_quarter * category * subcategory;
run;
proc freq data = day3.candy_sales_summary;
tables fiscal_year * fiscal_quarter * category * subcategory/list;
run;
Proc export data = day3.class outfile = "F:\Student\Mahesh\Files\class.xls" dbms = tab replace;
run;
Proc export data = day3.class outfile = "F:\Student\Mahesh\Files\class.csv" dbms = csv replace;
run;
Proc export data = day3.class outfile = "F:\Student\Mahesh\Files\class.txt" dbms = dlm replace; 
delimiter = ",";
run;
proc import datafile = "F:\Student\Mahesh\Files\class.csv" out = class dbms = csv replace;
run;
proc import datafile = "F:\Student\Mahesh\Files\class.xls" out = class1 dbms = tab replace;
run;
proc import datafile = "F:\Student\Mahesh\Files\class.txt" out = class2 dbms = dlm replace;
run;
proc import datafile = "F:\Student\Mahesh\Files\classdup.xls" out = classdup dbms = xls replace;
Sheet = "Sheet1";
run;
proc freq data = day3.class;
tables sex;
format sex $gender.;
run;
proc format;
value $gender "M" = "Male" "F" = "Female";
run;
