libname Day4 "F:\Student\Mahesh\Data1";
proc means data = day4.candy_sales_summary;
run;
proc means data = day4.candy_sales_summary;
var sale_amount units;
run;
proc means data = day4.candy_sales_summary sum std mean max n;
var sale_amount units;
run;
proc means data = day4.candy_sales_summary;
var sale_amount units;
class category subcategory;
run;
proc means data = day4.candy_sales_summary;
var sale_amount;
class category subcategory;
Output out = candy_means;
run;
proc means data = day4.candy_sales_summary noprint;
var sale_amount;
class category subcategory;
Output out = candy_means1 mean sum = Revenue;
run;
proc means data = day4.candy_sales_summary noprint;
var sale_amount;
class category subcategory;
Output out = candy_means2 sum = Revenue mean = Mean_Sales min = min_sales;
run;
proc sort data = day4.candy_sales_summary out = candy_04;
by category subcategory; 
run;
proc means data = candy_04 noprint;
var sale_amount;
by category subcategory;
Output out = Sorted_Candy04 sum = Revenue;
run;
proc summary data = day4.candy_sales_summary print;
var sale_amount;
run;
Proc tabulate data = day4.class;
var age height weight;
class sex; 
tables sex, (age height weight) * (mean sum);
run;
proc univariate data = day4.class;
var height;
run;
proc univariate data = day4.class noprint;
var height;
qqplot height;
run;
proc capability data = day4.class noprint;
var height;
ppplot height;
run;
